name:
  docgen
on:
  push
jobs:
  test:
    if: |
      !contains(github.event.head_commit.message, 'WIP')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-6'
      - run: "nimble -y install"
      - run: "nimble docgen"
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
